//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Models.dlgPerfilamiento {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SOAP ServerBinding", Namespace="http://produccion.clientesbayport.com/middleware")]
    public partial class SOAPServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback testOperationCompleted;
        
        private System.Threading.SendOrPostCallback procesarOfertaOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarCasoDecrimOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarIdCasoDecrimOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarCedulaDecrimOperationCompleted;
        
        private System.Threading.SendOrPostCallback generarSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarCondicionesOfertaOperationCompleted;
        
        private System.Threading.SendOrPostCallback rechazarCondicionesOfertaOperationCompleted;
        
        private System.Threading.SendOrPostCallback crearCasoDecrimOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaCasoDecrimOperationCompleted;
        
        private System.Threading.SendOrPostCallback pruebasDatalaftOperationCompleted;
        
        private System.Threading.SendOrPostCallback envioCorreoOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaReconocerOperationCompleted;
        
        private System.Threading.SendOrPostCallback aceptarOpcionSeguroOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizacionDatacreditoOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizacionDemandasOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizacionCifinOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SOAPServer() {
            this.Url = global::Models.Properties.Settings.Default.Models_dlgPerfilamiento_SOAP_Server;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event testCompletedEventHandler testCompleted;
        
        /// <remarks/>
        public event procesarOfertaCompletedEventHandler procesarOfertaCompleted;
        
        /// <remarks/>
        public event insertarCasoDecrimCompletedEventHandler insertarCasoDecrimCompleted;
        
        /// <remarks/>
        public event buscarIdCasoDecrimCompletedEventHandler buscarIdCasoDecrimCompleted;
        
        /// <remarks/>
        public event buscarCedulaDecrimCompletedEventHandler buscarCedulaDecrimCompleted;
        
        /// <remarks/>
        public event generarSmsCompletedEventHandler generarSmsCompleted;
        
        /// <remarks/>
        public event actualizarCondicionesOfertaCompletedEventHandler actualizarCondicionesOfertaCompleted;
        
        /// <remarks/>
        public event rechazarCondicionesOfertaCompletedEventHandler rechazarCondicionesOfertaCompleted;
        
        /// <remarks/>
        public event crearCasoDecrimCompletedEventHandler crearCasoDecrimCompleted;
        
        /// <remarks/>
        public event consultaCasoDecrimCompletedEventHandler consultaCasoDecrimCompleted;
        
        /// <remarks/>
        public event pruebasDatalaftCompletedEventHandler pruebasDatalaftCompleted;
        
        /// <remarks/>
        public event envioCorreoCompletedEventHandler envioCorreoCompleted;
        
        /// <remarks/>
        public event consultaReconocerCompletedEventHandler consultaReconocerCompleted;
        
        /// <remarks/>
        public event aceptarOpcionSeguroCompletedEventHandler aceptarOpcionSeguroCompleted;
        
        /// <remarks/>
        public event actualizacionDatacreditoCompletedEventHandler actualizacionDatacreditoCompleted;
        
        /// <remarks/>
        public event actualizacionDemandasCompletedEventHandler actualizacionDemandasCompleted;
        
        /// <remarks/>
        public event actualizacionCifinCompletedEventHandler actualizacionCifinCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/test", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string test(string usuario, string contrasena) {
            object[] results = this.Invoke("test", new object[] {
                        usuario,
                        contrasena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void testAsync(string usuario, string contrasena) {
            this.testAsync(usuario, contrasena, null);
        }
        
        /// <remarks/>
        public void testAsync(string usuario, string contrasena, object userState) {
            if ((this.testOperationCompleted == null)) {
                this.testOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestOperationCompleted);
            }
            this.InvokeAsync("test", new object[] {
                        usuario,
                        contrasena}, this.testOperationCompleted, userState);
        }
        
        private void OntestOperationCompleted(object arg) {
            if ((this.testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testCompleted(this, new testCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/procesarOferta", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string procesarOferta(
                    string usuario, 
                    string contrasena, 
                    string cedula, 
                    string nombre, 
                    string segundo_nombre, 
                    string primer_apellido, 
                    string segundo_apellido, 
                    int genero, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime fecha_nacimiento, 
                    int pagaduria, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime fecha_ingreso, 
                    int tipo_contrato, 
                    int tipo_credito, 
                    int linea_credito, 
                    int activo_pensionado, 
                    string docente, 
                    int plazo, 
                    int monto, 
                    int cuota1, 
                    int saldo1, 
                    string entidad1, 
                    int cuota2, 
                    int saldo2, 
                    string entidad2, 
                    int cuota3, 
                    int saldo3, 
                    string entidad3, 
                    int cuota4, 
                    int saldo4, 
                    string entidad4, 
                    int cuota5, 
                    int saldo5, 
                    string entidad5, 
                    int cuota6, 
                    int saldo6, 
                    string entidad6, 
                    int cuota_refinanciacion, 
                    int sucursal, 
                    string regional, 
                    int agente, 
                    int salario, 
                    string url_formato, 
                    int salud, 
                    int pension, 
                    int retefuente, 
                    int fondosolidaridad, 
                    int otros_descuentos, 
                    int compracartera_val, 
                    int ingresosadicionales, 
                    int otro_intento, 
                    int numero_carpeta, 
                    string telefono, 
                    int campo_numerico1, 
                    int campo_numerico2, 
                    int campo_numerico3, 
                    int campo_numerico4, 
                    int campo_numerico5, 
                    int campo_numerico6, 
                    int campo_numerico7, 
                    int campo_numerico8, 
                    int campo_numerico9, 
                    int campo_numerico10, 
                    int campo_numerico11, 
                    int campo_numerico12, 
                    int campo_numerico13, 
                    int campo_numerico14, 
                    int campo_numerico15, 
                    int campo_numerico16, 
                    int campo_numerico17, 
                    int campo_numerico18, 
                    int campo_numerico19, 
                    int campo_numerico20, 
                    string campo_texto1, 
                    string campo_texto2, 
                    string campo_texto3, 
                    string campo_texto4, 
                    string campo_texto5, 
                    string campo_texto6, 
                    string campo_texto7, 
                    string campo_texto8, 
                    string campo_texto9, 
                    string campo_texto10, 
                    string campo_texto11, 
                    string campo_texto12, 
                    string campo_texto13, 
                    string campo_texto14, 
                    string campo_texto15, 
                    string campo_texto16, 
                    string campo_texto17, 
                    string campo_texto18, 
                    string campo_texto19, 
                    string campo_texto20, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime campo_fecha1, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime campo_fecha2, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime campo_fecha3, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime campo_fecha4, 
                    [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime campo_fecha5, 
                    string convenio) {
            object[] results = this.Invoke("procesarOferta", new object[] {
                        usuario,
                        contrasena,
                        cedula,
                        nombre,
                        segundo_nombre,
                        primer_apellido,
                        segundo_apellido,
                        genero,
                        fecha_nacimiento,
                        pagaduria,
                        fecha_ingreso,
                        tipo_contrato,
                        tipo_credito,
                        linea_credito,
                        activo_pensionado,
                        docente,
                        plazo,
                        monto,
                        cuota1,
                        saldo1,
                        entidad1,
                        cuota2,
                        saldo2,
                        entidad2,
                        cuota3,
                        saldo3,
                        entidad3,
                        cuota4,
                        saldo4,
                        entidad4,
                        cuota5,
                        saldo5,
                        entidad5,
                        cuota6,
                        saldo6,
                        entidad6,
                        cuota_refinanciacion,
                        sucursal,
                        regional,
                        agente,
                        salario,
                        url_formato,
                        salud,
                        pension,
                        retefuente,
                        fondosolidaridad,
                        otros_descuentos,
                        compracartera_val,
                        ingresosadicionales,
                        otro_intento,
                        numero_carpeta,
                        telefono,
                        campo_numerico1,
                        campo_numerico2,
                        campo_numerico3,
                        campo_numerico4,
                        campo_numerico5,
                        campo_numerico6,
                        campo_numerico7,
                        campo_numerico8,
                        campo_numerico9,
                        campo_numerico10,
                        campo_numerico11,
                        campo_numerico12,
                        campo_numerico13,
                        campo_numerico14,
                        campo_numerico15,
                        campo_numerico16,
                        campo_numerico17,
                        campo_numerico18,
                        campo_numerico19,
                        campo_numerico20,
                        campo_texto1,
                        campo_texto2,
                        campo_texto3,
                        campo_texto4,
                        campo_texto5,
                        campo_texto6,
                        campo_texto7,
                        campo_texto8,
                        campo_texto9,
                        campo_texto10,
                        campo_texto11,
                        campo_texto12,
                        campo_texto13,
                        campo_texto14,
                        campo_texto15,
                        campo_texto16,
                        campo_texto17,
                        campo_texto18,
                        campo_texto19,
                        campo_texto20,
                        campo_fecha1,
                        campo_fecha2,
                        campo_fecha3,
                        campo_fecha4,
                        campo_fecha5,
                        convenio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void procesarOfertaAsync(
                    string usuario, 
                    string contrasena, 
                    string cedula, 
                    string nombre, 
                    string segundo_nombre, 
                    string primer_apellido, 
                    string segundo_apellido, 
                    int genero, 
                    System.DateTime fecha_nacimiento, 
                    int pagaduria, 
                    System.DateTime fecha_ingreso, 
                    int tipo_contrato, 
                    int tipo_credito, 
                    int linea_credito, 
                    int activo_pensionado, 
                    string docente, 
                    int plazo, 
                    int monto, 
                    int cuota1, 
                    int saldo1, 
                    string entidad1, 
                    int cuota2, 
                    int saldo2, 
                    string entidad2, 
                    int cuota3, 
                    int saldo3, 
                    string entidad3, 
                    int cuota4, 
                    int saldo4, 
                    string entidad4, 
                    int cuota5, 
                    int saldo5, 
                    string entidad5, 
                    int cuota6, 
                    int saldo6, 
                    string entidad6, 
                    int cuota_refinanciacion, 
                    int sucursal, 
                    string regional, 
                    int agente, 
                    int salario, 
                    string url_formato, 
                    int salud, 
                    int pension, 
                    int retefuente, 
                    int fondosolidaridad, 
                    int otros_descuentos, 
                    int compracartera_val, 
                    int ingresosadicionales, 
                    int otro_intento, 
                    int numero_carpeta, 
                    string telefono, 
                    int campo_numerico1, 
                    int campo_numerico2, 
                    int campo_numerico3, 
                    int campo_numerico4, 
                    int campo_numerico5, 
                    int campo_numerico6, 
                    int campo_numerico7, 
                    int campo_numerico8, 
                    int campo_numerico9, 
                    int campo_numerico10, 
                    int campo_numerico11, 
                    int campo_numerico12, 
                    int campo_numerico13, 
                    int campo_numerico14, 
                    int campo_numerico15, 
                    int campo_numerico16, 
                    int campo_numerico17, 
                    int campo_numerico18, 
                    int campo_numerico19, 
                    int campo_numerico20, 
                    string campo_texto1, 
                    string campo_texto2, 
                    string campo_texto3, 
                    string campo_texto4, 
                    string campo_texto5, 
                    string campo_texto6, 
                    string campo_texto7, 
                    string campo_texto8, 
                    string campo_texto9, 
                    string campo_texto10, 
                    string campo_texto11, 
                    string campo_texto12, 
                    string campo_texto13, 
                    string campo_texto14, 
                    string campo_texto15, 
                    string campo_texto16, 
                    string campo_texto17, 
                    string campo_texto18, 
                    string campo_texto19, 
                    string campo_texto20, 
                    System.DateTime campo_fecha1, 
                    System.DateTime campo_fecha2, 
                    System.DateTime campo_fecha3, 
                    System.DateTime campo_fecha4, 
                    System.DateTime campo_fecha5, 
                    string convenio) {
            this.procesarOfertaAsync(usuario, contrasena, cedula, nombre, segundo_nombre, primer_apellido, segundo_apellido, genero, fecha_nacimiento, pagaduria, fecha_ingreso, tipo_contrato, tipo_credito, linea_credito, activo_pensionado, docente, plazo, monto, cuota1, saldo1, entidad1, cuota2, saldo2, entidad2, cuota3, saldo3, entidad3, cuota4, saldo4, entidad4, cuota5, saldo5, entidad5, cuota6, saldo6, entidad6, cuota_refinanciacion, sucursal, regional, agente, salario, url_formato, salud, pension, retefuente, fondosolidaridad, otros_descuentos, compracartera_val, ingresosadicionales, otro_intento, numero_carpeta, telefono, campo_numerico1, campo_numerico2, campo_numerico3, campo_numerico4, campo_numerico5, campo_numerico6, campo_numerico7, campo_numerico8, campo_numerico9, campo_numerico10, campo_numerico11, campo_numerico12, campo_numerico13, campo_numerico14, campo_numerico15, campo_numerico16, campo_numerico17, campo_numerico18, campo_numerico19, campo_numerico20, campo_texto1, campo_texto2, campo_texto3, campo_texto4, campo_texto5, campo_texto6, campo_texto7, campo_texto8, campo_texto9, campo_texto10, campo_texto11, campo_texto12, campo_texto13, campo_texto14, campo_texto15, campo_texto16, campo_texto17, campo_texto18, campo_texto19, campo_texto20, campo_fecha1, campo_fecha2, campo_fecha3, campo_fecha4, campo_fecha5, convenio, null);
        }
        
        /// <remarks/>
        public void procesarOfertaAsync(
                    string usuario, 
                    string contrasena, 
                    string cedula, 
                    string nombre, 
                    string segundo_nombre, 
                    string primer_apellido, 
                    string segundo_apellido, 
                    int genero, 
                    System.DateTime fecha_nacimiento, 
                    int pagaduria, 
                    System.DateTime fecha_ingreso, 
                    int tipo_contrato, 
                    int tipo_credito, 
                    int linea_credito, 
                    int activo_pensionado, 
                    string docente, 
                    int plazo, 
                    int monto, 
                    int cuota1, 
                    int saldo1, 
                    string entidad1, 
                    int cuota2, 
                    int saldo2, 
                    string entidad2, 
                    int cuota3, 
                    int saldo3, 
                    string entidad3, 
                    int cuota4, 
                    int saldo4, 
                    string entidad4, 
                    int cuota5, 
                    int saldo5, 
                    string entidad5, 
                    int cuota6, 
                    int saldo6, 
                    string entidad6, 
                    int cuota_refinanciacion, 
                    int sucursal, 
                    string regional, 
                    int agente, 
                    int salario, 
                    string url_formato, 
                    int salud, 
                    int pension, 
                    int retefuente, 
                    int fondosolidaridad, 
                    int otros_descuentos, 
                    int compracartera_val, 
                    int ingresosadicionales, 
                    int otro_intento, 
                    int numero_carpeta, 
                    string telefono, 
                    int campo_numerico1, 
                    int campo_numerico2, 
                    int campo_numerico3, 
                    int campo_numerico4, 
                    int campo_numerico5, 
                    int campo_numerico6, 
                    int campo_numerico7, 
                    int campo_numerico8, 
                    int campo_numerico9, 
                    int campo_numerico10, 
                    int campo_numerico11, 
                    int campo_numerico12, 
                    int campo_numerico13, 
                    int campo_numerico14, 
                    int campo_numerico15, 
                    int campo_numerico16, 
                    int campo_numerico17, 
                    int campo_numerico18, 
                    int campo_numerico19, 
                    int campo_numerico20, 
                    string campo_texto1, 
                    string campo_texto2, 
                    string campo_texto3, 
                    string campo_texto4, 
                    string campo_texto5, 
                    string campo_texto6, 
                    string campo_texto7, 
                    string campo_texto8, 
                    string campo_texto9, 
                    string campo_texto10, 
                    string campo_texto11, 
                    string campo_texto12, 
                    string campo_texto13, 
                    string campo_texto14, 
                    string campo_texto15, 
                    string campo_texto16, 
                    string campo_texto17, 
                    string campo_texto18, 
                    string campo_texto19, 
                    string campo_texto20, 
                    System.DateTime campo_fecha1, 
                    System.DateTime campo_fecha2, 
                    System.DateTime campo_fecha3, 
                    System.DateTime campo_fecha4, 
                    System.DateTime campo_fecha5, 
                    string convenio, 
                    object userState) {
            if ((this.procesarOfertaOperationCompleted == null)) {
                this.procesarOfertaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocesarOfertaOperationCompleted);
            }
            this.InvokeAsync("procesarOferta", new object[] {
                        usuario,
                        contrasena,
                        cedula,
                        nombre,
                        segundo_nombre,
                        primer_apellido,
                        segundo_apellido,
                        genero,
                        fecha_nacimiento,
                        pagaduria,
                        fecha_ingreso,
                        tipo_contrato,
                        tipo_credito,
                        linea_credito,
                        activo_pensionado,
                        docente,
                        plazo,
                        monto,
                        cuota1,
                        saldo1,
                        entidad1,
                        cuota2,
                        saldo2,
                        entidad2,
                        cuota3,
                        saldo3,
                        entidad3,
                        cuota4,
                        saldo4,
                        entidad4,
                        cuota5,
                        saldo5,
                        entidad5,
                        cuota6,
                        saldo6,
                        entidad6,
                        cuota_refinanciacion,
                        sucursal,
                        regional,
                        agente,
                        salario,
                        url_formato,
                        salud,
                        pension,
                        retefuente,
                        fondosolidaridad,
                        otros_descuentos,
                        compracartera_val,
                        ingresosadicionales,
                        otro_intento,
                        numero_carpeta,
                        telefono,
                        campo_numerico1,
                        campo_numerico2,
                        campo_numerico3,
                        campo_numerico4,
                        campo_numerico5,
                        campo_numerico6,
                        campo_numerico7,
                        campo_numerico8,
                        campo_numerico9,
                        campo_numerico10,
                        campo_numerico11,
                        campo_numerico12,
                        campo_numerico13,
                        campo_numerico14,
                        campo_numerico15,
                        campo_numerico16,
                        campo_numerico17,
                        campo_numerico18,
                        campo_numerico19,
                        campo_numerico20,
                        campo_texto1,
                        campo_texto2,
                        campo_texto3,
                        campo_texto4,
                        campo_texto5,
                        campo_texto6,
                        campo_texto7,
                        campo_texto8,
                        campo_texto9,
                        campo_texto10,
                        campo_texto11,
                        campo_texto12,
                        campo_texto13,
                        campo_texto14,
                        campo_texto15,
                        campo_texto16,
                        campo_texto17,
                        campo_texto18,
                        campo_texto19,
                        campo_texto20,
                        campo_fecha1,
                        campo_fecha2,
                        campo_fecha3,
                        campo_fecha4,
                        campo_fecha5,
                        convenio}, this.procesarOfertaOperationCompleted, userState);
        }
        
        private void OnprocesarOfertaOperationCompleted(object arg) {
            if ((this.procesarOfertaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.procesarOfertaCompleted(this, new procesarOfertaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/insertarCasoDecrim", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string insertarCasoDecrim(string usuario, string contrasena, int carpeta, string UUID, string observaciones, int idTipIde, int NIdentificacion, string pApellido, string sApellido, string pNombre, string sNombre, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime fecNac, string sexo, string rh, string imagenes) {
            object[] results = this.Invoke("insertarCasoDecrim", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        UUID,
                        observaciones,
                        idTipIde,
                        NIdentificacion,
                        pApellido,
                        sApellido,
                        pNombre,
                        sNombre,
                        fecNac,
                        sexo,
                        rh,
                        imagenes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertarCasoDecrimAsync(string usuario, string contrasena, int carpeta, string UUID, string observaciones, int idTipIde, int NIdentificacion, string pApellido, string sApellido, string pNombre, string sNombre, System.DateTime fecNac, string sexo, string rh, string imagenes) {
            this.insertarCasoDecrimAsync(usuario, contrasena, carpeta, UUID, observaciones, idTipIde, NIdentificacion, pApellido, sApellido, pNombre, sNombre, fecNac, sexo, rh, imagenes, null);
        }
        
        /// <remarks/>
        public void insertarCasoDecrimAsync(
                    string usuario, 
                    string contrasena, 
                    int carpeta, 
                    string UUID, 
                    string observaciones, 
                    int idTipIde, 
                    int NIdentificacion, 
                    string pApellido, 
                    string sApellido, 
                    string pNombre, 
                    string sNombre, 
                    System.DateTime fecNac, 
                    string sexo, 
                    string rh, 
                    string imagenes, 
                    object userState) {
            if ((this.insertarCasoDecrimOperationCompleted == null)) {
                this.insertarCasoDecrimOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarCasoDecrimOperationCompleted);
            }
            this.InvokeAsync("insertarCasoDecrim", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        UUID,
                        observaciones,
                        idTipIde,
                        NIdentificacion,
                        pApellido,
                        sApellido,
                        pNombre,
                        sNombre,
                        fecNac,
                        sexo,
                        rh,
                        imagenes}, this.insertarCasoDecrimOperationCompleted, userState);
        }
        
        private void OninsertarCasoDecrimOperationCompleted(object arg) {
            if ((this.insertarCasoDecrimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarCasoDecrimCompleted(this, new insertarCasoDecrimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/buscarIdCasoDecrim", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string buscarIdCasoDecrim(string usuario, string contrasena, int id_caso, int carpeta, string UUID) {
            object[] results = this.Invoke("buscarIdCasoDecrim", new object[] {
                        usuario,
                        contrasena,
                        id_caso,
                        carpeta,
                        UUID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void buscarIdCasoDecrimAsync(string usuario, string contrasena, int id_caso, int carpeta, string UUID) {
            this.buscarIdCasoDecrimAsync(usuario, contrasena, id_caso, carpeta, UUID, null);
        }
        
        /// <remarks/>
        public void buscarIdCasoDecrimAsync(string usuario, string contrasena, int id_caso, int carpeta, string UUID, object userState) {
            if ((this.buscarIdCasoDecrimOperationCompleted == null)) {
                this.buscarIdCasoDecrimOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarIdCasoDecrimOperationCompleted);
            }
            this.InvokeAsync("buscarIdCasoDecrim", new object[] {
                        usuario,
                        contrasena,
                        id_caso,
                        carpeta,
                        UUID}, this.buscarIdCasoDecrimOperationCompleted, userState);
        }
        
        private void OnbuscarIdCasoDecrimOperationCompleted(object arg) {
            if ((this.buscarIdCasoDecrimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarIdCasoDecrimCompleted(this, new buscarIdCasoDecrimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/buscarCedulaDecrim", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string buscarCedulaDecrim(string usuario, string contrasena, string cedula, int carpeta, string UUID) {
            object[] results = this.Invoke("buscarCedulaDecrim", new object[] {
                        usuario,
                        contrasena,
                        cedula,
                        carpeta,
                        UUID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void buscarCedulaDecrimAsync(string usuario, string contrasena, string cedula, int carpeta, string UUID) {
            this.buscarCedulaDecrimAsync(usuario, contrasena, cedula, carpeta, UUID, null);
        }
        
        /// <remarks/>
        public void buscarCedulaDecrimAsync(string usuario, string contrasena, string cedula, int carpeta, string UUID, object userState) {
            if ((this.buscarCedulaDecrimOperationCompleted == null)) {
                this.buscarCedulaDecrimOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarCedulaDecrimOperationCompleted);
            }
            this.InvokeAsync("buscarCedulaDecrim", new object[] {
                        usuario,
                        contrasena,
                        cedula,
                        carpeta,
                        UUID}, this.buscarCedulaDecrimOperationCompleted, userState);
        }
        
        private void OnbuscarCedulaDecrimOperationCompleted(object arg) {
            if ((this.buscarCedulaDecrimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarCedulaDecrimCompleted(this, new buscarCedulaDecrimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/generarSms", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string generarSms(string usuario, string contrasena, string celular, string mensaje) {
            object[] results = this.Invoke("generarSms", new object[] {
                        usuario,
                        contrasena,
                        celular,
                        mensaje});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void generarSmsAsync(string usuario, string contrasena, string celular, string mensaje) {
            this.generarSmsAsync(usuario, contrasena, celular, mensaje, null);
        }
        
        /// <remarks/>
        public void generarSmsAsync(string usuario, string contrasena, string celular, string mensaje, object userState) {
            if ((this.generarSmsOperationCompleted == null)) {
                this.generarSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerarSmsOperationCompleted);
            }
            this.InvokeAsync("generarSms", new object[] {
                        usuario,
                        contrasena,
                        celular,
                        mensaje}, this.generarSmsOperationCompleted, userState);
        }
        
        private void OngenerarSmsOperationCompleted(object arg) {
            if ((this.generarSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generarSmsCompleted(this, new generarSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/actualizarCondicionesOferta", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string actualizarCondicionesOferta(string usuario, string contrasena, int carpeta, string tasa, int plazo, int monto) {
            object[] results = this.Invoke("actualizarCondicionesOferta", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        tasa,
                        plazo,
                        monto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarCondicionesOfertaAsync(string usuario, string contrasena, int carpeta, string tasa, int plazo, int monto) {
            this.actualizarCondicionesOfertaAsync(usuario, contrasena, carpeta, tasa, plazo, monto, null);
        }
        
        /// <remarks/>
        public void actualizarCondicionesOfertaAsync(string usuario, string contrasena, int carpeta, string tasa, int plazo, int monto, object userState) {
            if ((this.actualizarCondicionesOfertaOperationCompleted == null)) {
                this.actualizarCondicionesOfertaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarCondicionesOfertaOperationCompleted);
            }
            this.InvokeAsync("actualizarCondicionesOferta", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        tasa,
                        plazo,
                        monto}, this.actualizarCondicionesOfertaOperationCompleted, userState);
        }
        
        private void OnactualizarCondicionesOfertaOperationCompleted(object arg) {
            if ((this.actualizarCondicionesOfertaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarCondicionesOfertaCompleted(this, new actualizarCondicionesOfertaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/actualizarCondicionesOferta", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string rechazarCondicionesOferta(string usuario, string contrasena, int carpeta, string observaciones, string agente) {
            object[] results = this.Invoke("rechazarCondicionesOferta", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        observaciones,
                        agente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void rechazarCondicionesOfertaAsync(string usuario, string contrasena, int carpeta, string observaciones, string agente) {
            this.rechazarCondicionesOfertaAsync(usuario, contrasena, carpeta, observaciones, agente, null);
        }
        
        /// <remarks/>
        public void rechazarCondicionesOfertaAsync(string usuario, string contrasena, int carpeta, string observaciones, string agente, object userState) {
            if ((this.rechazarCondicionesOfertaOperationCompleted == null)) {
                this.rechazarCondicionesOfertaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrechazarCondicionesOfertaOperationCompleted);
            }
            this.InvokeAsync("rechazarCondicionesOferta", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        observaciones,
                        agente}, this.rechazarCondicionesOfertaOperationCompleted, userState);
        }
        
        private void OnrechazarCondicionesOfertaOperationCompleted(object arg) {
            if ((this.rechazarCondicionesOfertaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rechazarCondicionesOfertaCompleted(this, new rechazarCondicionesOfertaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/crearCasoDecrim", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string crearCasoDecrim(string usuario, string contrasena, string carpeta, string identificacion) {
            object[] results = this.Invoke("crearCasoDecrim", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        identificacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void crearCasoDecrimAsync(string usuario, string contrasena, string carpeta, string identificacion) {
            this.crearCasoDecrimAsync(usuario, contrasena, carpeta, identificacion, null);
        }
        
        /// <remarks/>
        public void crearCasoDecrimAsync(string usuario, string contrasena, string carpeta, string identificacion, object userState) {
            if ((this.crearCasoDecrimOperationCompleted == null)) {
                this.crearCasoDecrimOperationCompleted = new System.Threading.SendOrPostCallback(this.OncrearCasoDecrimOperationCompleted);
            }
            this.InvokeAsync("crearCasoDecrim", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        identificacion}, this.crearCasoDecrimOperationCompleted, userState);
        }
        
        private void OncrearCasoDecrimOperationCompleted(object arg) {
            if ((this.crearCasoDecrimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.crearCasoDecrimCompleted(this, new crearCasoDecrimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/consultaCasoDecrim", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string consultaCasoDecrim(string usuario, string contrasena, string carpeta, string idCaso) {
            object[] results = this.Invoke("consultaCasoDecrim", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        idCaso});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaCasoDecrimAsync(string usuario, string contrasena, string carpeta, string idCaso) {
            this.consultaCasoDecrimAsync(usuario, contrasena, carpeta, idCaso, null);
        }
        
        /// <remarks/>
        public void consultaCasoDecrimAsync(string usuario, string contrasena, string carpeta, string idCaso, object userState) {
            if ((this.consultaCasoDecrimOperationCompleted == null)) {
                this.consultaCasoDecrimOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaCasoDecrimOperationCompleted);
            }
            this.InvokeAsync("consultaCasoDecrim", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        idCaso}, this.consultaCasoDecrimOperationCompleted, userState);
        }
        
        private void OnconsultaCasoDecrimOperationCompleted(object arg) {
            if ((this.consultaCasoDecrimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaCasoDecrimCompleted(this, new consultaCasoDecrimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/pruebasDatalaft", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string pruebasDatalaft(string identificacion, string nombre) {
            object[] results = this.Invoke("pruebasDatalaft", new object[] {
                        identificacion,
                        nombre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pruebasDatalaftAsync(string identificacion, string nombre) {
            this.pruebasDatalaftAsync(identificacion, nombre, null);
        }
        
        /// <remarks/>
        public void pruebasDatalaftAsync(string identificacion, string nombre, object userState) {
            if ((this.pruebasDatalaftOperationCompleted == null)) {
                this.pruebasDatalaftOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpruebasDatalaftOperationCompleted);
            }
            this.InvokeAsync("pruebasDatalaft", new object[] {
                        identificacion,
                        nombre}, this.pruebasDatalaftOperationCompleted, userState);
        }
        
        private void OnpruebasDatalaftOperationCompleted(object arg) {
            if ((this.pruebasDatalaftCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pruebasDatalaftCompleted(this, new pruebasDatalaftCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/envioCorreo", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string envioCorreo(string cuerpo) {
            object[] results = this.Invoke("envioCorreo", new object[] {
                        cuerpo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void envioCorreoAsync(string cuerpo) {
            this.envioCorreoAsync(cuerpo, null);
        }
        
        /// <remarks/>
        public void envioCorreoAsync(string cuerpo, object userState) {
            if ((this.envioCorreoOperationCompleted == null)) {
                this.envioCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenvioCorreoOperationCompleted);
            }
            this.InvokeAsync("envioCorreo", new object[] {
                        cuerpo}, this.envioCorreoOperationCompleted, userState);
        }
        
        private void OnenvioCorreoOperationCompleted(object arg) {
            if ((this.envioCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.envioCorreoCompleted(this, new envioCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/consultaReconocer", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string consultaReconocer(string cedula, string apellido) {
            object[] results = this.Invoke("consultaReconocer", new object[] {
                        cedula,
                        apellido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaReconocerAsync(string cedula, string apellido) {
            this.consultaReconocerAsync(cedula, apellido, null);
        }
        
        /// <remarks/>
        public void consultaReconocerAsync(string cedula, string apellido, object userState) {
            if ((this.consultaReconocerOperationCompleted == null)) {
                this.consultaReconocerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaReconocerOperationCompleted);
            }
            this.InvokeAsync("consultaReconocer", new object[] {
                        cedula,
                        apellido}, this.consultaReconocerOperationCompleted, userState);
        }
        
        private void OnconsultaReconocerOperationCompleted(object arg) {
            if ((this.consultaReconocerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaReconocerCompleted(this, new consultaReconocerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/aceptarOpcionSeguro", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string aceptarOpcionSeguro(string usuario, string contrasena, int carpeta, int codigoPlan, int valorPlan) {
            object[] results = this.Invoke("aceptarOpcionSeguro", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        codigoPlan,
                        valorPlan});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aceptarOpcionSeguroAsync(string usuario, string contrasena, int carpeta, int codigoPlan, int valorPlan) {
            this.aceptarOpcionSeguroAsync(usuario, contrasena, carpeta, codigoPlan, valorPlan, null);
        }
        
        /// <remarks/>
        public void aceptarOpcionSeguroAsync(string usuario, string contrasena, int carpeta, int codigoPlan, int valorPlan, object userState) {
            if ((this.aceptarOpcionSeguroOperationCompleted == null)) {
                this.aceptarOpcionSeguroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaceptarOpcionSeguroOperationCompleted);
            }
            this.InvokeAsync("aceptarOpcionSeguro", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        codigoPlan,
                        valorPlan}, this.aceptarOpcionSeguroOperationCompleted, userState);
        }
        
        private void OnaceptarOpcionSeguroOperationCompleted(object arg) {
            if ((this.aceptarOpcionSeguroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aceptarOpcionSeguroCompleted(this, new aceptarOpcionSeguroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/actualizacionDatacredito", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string actualizacionDatacredito(string usuario, string contrasena, int carpeta, string primerApellido, int cedula) {
            object[] results = this.Invoke("actualizacionDatacredito", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        primerApellido,
                        cedula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void actualizacionDatacreditoAsync(string usuario, string contrasena, int carpeta, string primerApellido, int cedula) {
            this.actualizacionDatacreditoAsync(usuario, contrasena, carpeta, primerApellido, cedula, null);
        }
        
        /// <remarks/>
        public void actualizacionDatacreditoAsync(string usuario, string contrasena, int carpeta, string primerApellido, int cedula, object userState) {
            if ((this.actualizacionDatacreditoOperationCompleted == null)) {
                this.actualizacionDatacreditoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizacionDatacreditoOperationCompleted);
            }
            this.InvokeAsync("actualizacionDatacredito", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        primerApellido,
                        cedula}, this.actualizacionDatacreditoOperationCompleted, userState);
        }
        
        private void OnactualizacionDatacreditoOperationCompleted(object arg) {
            if ((this.actualizacionDatacreditoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizacionDatacreditoCompleted(this, new actualizacionDatacreditoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/actualizacionDemandas", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string actualizacionDemandas(string usuario, string contrasena, int carpeta, int cedula) {
            object[] results = this.Invoke("actualizacionDemandas", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        cedula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void actualizacionDemandasAsync(string usuario, string contrasena, int carpeta, int cedula) {
            this.actualizacionDemandasAsync(usuario, contrasena, carpeta, cedula, null);
        }
        
        /// <remarks/>
        public void actualizacionDemandasAsync(string usuario, string contrasena, int carpeta, int cedula, object userState) {
            if ((this.actualizacionDemandasOperationCompleted == null)) {
                this.actualizacionDemandasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizacionDemandasOperationCompleted);
            }
            this.InvokeAsync("actualizacionDemandas", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        cedula}, this.actualizacionDemandasOperationCompleted, userState);
        }
        
        private void OnactualizacionDemandasOperationCompleted(object arg) {
            if ((this.actualizacionDemandasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizacionDemandasCompleted(this, new actualizacionDemandasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:http://produccion.clientesbayport.com/middleware/actualizacionCifin", RequestNamespace="urn:SOAPServerWSDL", ResponseNamespace="urn:SOAPServerWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("notificacion")]
        public string actualizacionCifin(string usuario, string contrasena, int carpeta, int cedula) {
            object[] results = this.Invoke("actualizacionCifin", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        cedula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void actualizacionCifinAsync(string usuario, string contrasena, int carpeta, int cedula) {
            this.actualizacionCifinAsync(usuario, contrasena, carpeta, cedula, null);
        }
        
        /// <remarks/>
        public void actualizacionCifinAsync(string usuario, string contrasena, int carpeta, int cedula, object userState) {
            if ((this.actualizacionCifinOperationCompleted == null)) {
                this.actualizacionCifinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizacionCifinOperationCompleted);
            }
            this.InvokeAsync("actualizacionCifin", new object[] {
                        usuario,
                        contrasena,
                        carpeta,
                        cedula}, this.actualizacionCifinOperationCompleted, userState);
        }
        
        private void OnactualizacionCifinOperationCompleted(object arg) {
            if ((this.actualizacionCifinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizacionCifinCompleted(this, new actualizacionCifinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void testCompletedEventHandler(object sender, testCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void procesarOfertaCompletedEventHandler(object sender, procesarOfertaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class procesarOfertaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal procesarOfertaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void insertarCasoDecrimCompletedEventHandler(object sender, insertarCasoDecrimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarCasoDecrimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarCasoDecrimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void buscarIdCasoDecrimCompletedEventHandler(object sender, buscarIdCasoDecrimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarIdCasoDecrimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarIdCasoDecrimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void buscarCedulaDecrimCompletedEventHandler(object sender, buscarCedulaDecrimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarCedulaDecrimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarCedulaDecrimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void generarSmsCompletedEventHandler(object sender, generarSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generarSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generarSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void actualizarCondicionesOfertaCompletedEventHandler(object sender, actualizarCondicionesOfertaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarCondicionesOfertaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarCondicionesOfertaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void rechazarCondicionesOfertaCompletedEventHandler(object sender, rechazarCondicionesOfertaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rechazarCondicionesOfertaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rechazarCondicionesOfertaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void crearCasoDecrimCompletedEventHandler(object sender, crearCasoDecrimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class crearCasoDecrimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal crearCasoDecrimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void consultaCasoDecrimCompletedEventHandler(object sender, consultaCasoDecrimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaCasoDecrimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaCasoDecrimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void pruebasDatalaftCompletedEventHandler(object sender, pruebasDatalaftCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pruebasDatalaftCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pruebasDatalaftCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void envioCorreoCompletedEventHandler(object sender, envioCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class envioCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal envioCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void consultaReconocerCompletedEventHandler(object sender, consultaReconocerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaReconocerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaReconocerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void aceptarOpcionSeguroCompletedEventHandler(object sender, aceptarOpcionSeguroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aceptarOpcionSeguroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aceptarOpcionSeguroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void actualizacionDatacreditoCompletedEventHandler(object sender, actualizacionDatacreditoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizacionDatacreditoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizacionDatacreditoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void actualizacionDemandasCompletedEventHandler(object sender, actualizacionDemandasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizacionDemandasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizacionDemandasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void actualizacionCifinCompletedEventHandler(object sender, actualizacionCifinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizacionCifinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizacionCifinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591