CREATE TABLE DLG_PARAM_AVISOS(
    SECUENCIA NUMBER NOT NULL PRIMARY KEY,
    TITULO_AVISO VARCHAR2(100) NOT NULL,
    CONTENIDO_AVISO VARCHAR2(1000),
    FUENTE_AVISO NUMBER NOT NULL,
    URL_IMAGENES CLOB,
    ENLACES CLOB,
    FECHA_INICIO_VIGENCIA DATE,
    FECHA_FIN_VIGENCIA DATE
);
CREATE SEQUENCE dlg_seq_avisos
start with 1
increment by 1;